name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v1
      - name: "Install sdl"
        run: "sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev"
      - name: Run tests
        run: go test -v -covermode=atomic -race ./...
